/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
//package payroll_system;


import java.rmi.RemoteException;
import java.rmi.registry.LocateRegistry;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import payrol.Interface.emp_detail_Interface;
import java.rmi.registry.Registry;
import javax.swing.*;

/**
 *
 * @author Surya
 */
public class emp_detail extends javax.swing.JFrame {

    /**
     * Creates new form emp_detail
     */
    public emp_detail() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem3 = new javax.swing.JCheckBoxMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cmbgender = new javax.swing.JComboBox<String>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cmbcategory = new javax.swing.JComboBox<String>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtacct = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtpan = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        cmbmarital = new javax.swing.JComboBox<String>();
        jLabel15 = new javax.swing.JLabel();
        cmbmqualify = new javax.swing.JComboBox<String>();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        caddress = new javax.swing.JTextArea();
        jLabel17 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jScrollPane3 = new javax.swing.JScrollPane();
        paddress = new javax.swing.JTextArea();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtmname = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtsname = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        cmbfqualify = new javax.swing.JComboBox<String>();
        jLabel23 = new javax.swing.JLabel();
        txtfname = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        cmbsqualify = new javax.swing.JComboBox<String>();
        jLabel25 = new javax.swing.JLabel();
        txtchild = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        cmbbranch = new javax.swing.JComboBox<String>();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        txtdor = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        cmbdept = new javax.swing.JComboBox<String>();
        cmbqualify = new javax.swing.JComboBox<String>();
        jLabel31 = new javax.swing.JLabel();
        cmbdesig = new javax.swing.JComboBox<String>();
        dd = new com.toedter.calendar.JDateChooser();
        doj = new com.toedter.calendar.JDateChooser();
        btnback = new javax.swing.JButton();
        btnsubmit = new javax.swing.JButton();
        txtadhar = new javax.swing.JFormattedTextField();
        cmbreligion = new javax.swing.JComboBox();
        cmbnationality = new javax.swing.JComboBox();
        txtmobile = new javax.swing.JFormattedTextField();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("jCheckBoxMenuItem2");

        jCheckBoxMenuItem3.setSelected(true);
        jCheckBoxMenuItem3.setText("jCheckBoxMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Employee Detail");

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jPanel2.setBackground(new java.awt.Color(173, 216, 230));
        jPanel2.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, new javax.swing.border.MatteBorder(null)));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setLabelFor(jPanel2);
        jLabel1.setText("--------------------Personal Detail--------------------");
        jLabel1.setToolTipText("");

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        jLabel3.setText(" Name");

        txtname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        jLabel4.setText("Gender");

        cmbgender.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmbgender.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "[--SELECT ONE--]", "Male", "Female", "Others" }));
        cmbgender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbgenderActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        jLabel5.setText("Date of Birth");

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        jLabel6.setText("Category");

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        jLabel7.setText("Religion");

        cmbcategory.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmbcategory.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "[--SELECT ONE--]", "Generel", "OBC", "SC/ST" }));

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        jLabel8.setText("Nationality");

        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        jLabel9.setText("Aadhar Number");

        jLabel10.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        jLabel10.setText("PAN Number");

        jLabel11.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        jLabel11.setText("Account Number");

        txtacct.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        jLabel12.setText("Email ID");

        txtemail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemailActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        jLabel13.setText("Mobile Number");

        txtpan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        jLabel14.setText("Marital Status");

        cmbmarital.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmbmarital.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "[---SELECT ONE---]", "Single", "Married" }));

        jLabel15.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        jLabel15.setText("Educational Qualification");

        cmbmqualify.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmbmqualify.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "[--SELECT ONE--]", "Matric", "Inter", "Graduate", "Post Graduate", "Doctorate", "Post Doctorate" }));

        jLabel16.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        jLabel16.setText("Current address");

        caddress.setColumns(20);
        caddress.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        caddress.setLineWrap(true);
        caddress.setRows(5);
        jScrollPane2.setViewportView(caddress);

        jLabel17.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        jLabel17.setText("Permanent address");

        jCheckBox1.setText("same as current address");
        jCheckBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox1MouseClicked(evt);
            }
        });

        paddress.setColumns(20);
        paddress.setLineWrap(true);
        paddress.setRows(5);
        jScrollPane3.setViewportView(paddress);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("--------------------Family Details-------------------");
        jLabel18.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel19.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        jLabel19.setText("Mother's Name");

        txtmname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel20.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        jLabel20.setText("Educational Qualification");

        jLabel21.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        jLabel21.setText("Father's Name");

        txtsname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel22.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        jLabel22.setText("Educational Qualification");

        cmbfqualify.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmbfqualify.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "[--SELECT ONE--]", "Matric", "Inter", "Graduate", "Post Graduate", "Doctorate", "Post Doctorate" }));

        jLabel23.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        jLabel23.setText("Spouse Name");

        txtfname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel24.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        jLabel24.setText("Educational Qualification");

        cmbsqualify.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmbsqualify.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "[--SELECT ONE--]", "Matric", "Inter", "Graduate", "Post Graduate", "Doctorate", "Post Doctorate", "N/A" }));

        jLabel25.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        jLabel25.setText("Number of children");

        txtchild.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("--------------Working Details------------");

        jLabel27.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        jLabel27.setText("Branch Name");

        cmbbranch.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmbbranch.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "[--SELECT ONE--]", "Bengaluru", "Kolkata", "Lucknow", "Mumbai", "New Delhi", "Patna", "Raipur", "Ranchi", " " }));

        jLabel28.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        jLabel28.setText("Date of joining");

        jLabel29.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        jLabel29.setText("Date of retirement");

        txtdor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtdor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdorActionPerformed(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        jLabel30.setText("Department");

        cmbdept.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmbdept.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "[--SELECT ONE--]", "Audit", "Deposite", "Hindi", "Human Resource", "IT", "Law", "Loan", "Operation", "Rural Development" }));
        cmbdept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbdeptActionPerformed(evt);
            }
        });

        cmbqualify.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmbqualify.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "[--SELECT ONE--]", "Matric", "Inter", "Graduate", "Post Graduate", "Doctorate", "Post Doctorate" }));

        jLabel31.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        jLabel31.setText("Designation");

        cmbdesig.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmbdesig.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "[--SELECT ONE--]", "Clerk", "Assistant Manager", "Manager", "Senior Manager", "Chief Manager", "Assistant General Manager", "Deputy General Manager", "General Manager", "Executive Director", "Chairman" }));

        btnback.setFont(new java.awt.Font("Adobe Caslon Pro Bold", 1, 24)); // NOI18N
        btnback.setText("BACK");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        btnsubmit.setFont(new java.awt.Font("Adobe Caslon Pro Bold", 1, 24)); // NOI18N
        btnsubmit.setText("SUBMIT");
        btnsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsubmitActionPerformed(evt);
            }
        });

        txtadhar.setBorder(null);
        try {
            txtadhar.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        cmbreligion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmbreligion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "[--SELECT ONE--]", "HINDU", "MUSLIM", "SIKH", "CRISTIAN", "BUDDHISM", "OTHERS" }));

        cmbnationality.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmbnationality.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "[--SELECT ONE--]", "INDIAN", "AFGHAN", "BURMESE", "BHUTANESE", "CHINESE", "NEPALESE", "SINHALESE", " ", " " }));

        txtmobile.setBorder(null);
        try {
            txtmobile.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtmobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmobileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1366, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(100, 100, 100)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(80, 80, 80)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtname)
                                        .addComponent(cmbgender, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cmbcategory, 0, 200, Short.MAX_VALUE)
                                        .addComponent(txtacct)
                                        .addComponent(txtemail)
                                        .addComponent(txtpan)
                                        .addComponent(dd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtadhar)
                                        .addComponent(cmbreligion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cmbnationality, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(300, 300, 300)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(txtmobile, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(80, 80, 80)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cmbmarital, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane2)
                                .addComponent(jCheckBox1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane3)
                                .addComponent(cmbqualify, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 1366, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(100, 100, 100)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(81, 81, 81)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtmname, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                .addComponent(txtsname)
                                .addComponent(txtfname)
                                .addComponent(txtchild))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(66, 66, 66)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cmbfqualify, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cmbmqualify, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cmbsqualify, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(126, 126, 126)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 1366, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnback, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnsubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel29))
                                .addGap(92, 92, 92)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cmbbranch, 0, 200, Short.MAX_VALUE)
                                    .addComponent(txtdor)
                                    .addComponent(doj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(268, 268, 268)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(97, 97, 97)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cmbdept, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbdesig, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(1045, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                                .addComponent(cmbgender))
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                            .addComponent(dd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbcategory, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbreligion, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(cmbmarital, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbqualify, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBox1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbnationality, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtadhar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtpan, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtacct, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtmobile, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtmname, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmbmqualify, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmbfqualify, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtfname, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(txtsname, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbsqualify, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(txtchild, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbbranch, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel30)
                            .addComponent(cmbdept, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                            .addComponent(doj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel31)
                        .addComponent(cmbdesig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtdor, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnback, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );

        jLabel26.getAccessibleContext().setAccessibleName("-----------------------------Working Details---------------------------");

        jScrollPane1.setViewportView(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1378, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 956, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmbgenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbgenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbgenderActionPerformed

    private void jCheckBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox1MouseClicked
               if(jCheckBox1.isSelected())  
                paddress.setText(caddress.getText());
                   //jTextArea2.setText(text);
               
              // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1MouseClicked

    private void txtdorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdorActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void btnsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsubmitActionPerformed
        // TODO add your handling code here:
       // String id=txtid.getText();
        
        String name=txtname.getText();
        if(txtname.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(emp_detail.this,"Please enter the name of employee");
            txtname.grabFocus();
            return;
        }
       String gender=(String)cmbgender.getSelectedItem();
       if(cmbgender.getSelectedIndex()==0)
       {
           JOptionPane.showMessageDialog(emp_detail.this,"Please select the gender");
           cmbgender.grabFocus();
           return;
       }
        //SimpleDateFormat formatter=new SimpleDateFormat("MMM DD, YYYY");
                // String dob=rs.getString("dob");
                 // Date d=formatter.parse(dob);
        Date dp=dd.getDate();
         if(dd.getDate()==null)
        {
            JOptionPane.showMessageDialog(emp_detail.this,"Please select the date of birth");
            return;
        }
        Calendar cal=Calendar.getInstance();
        cal.setTime(dp);
        int day=cal.get(Calendar.DAY_OF_MONTH);
         int year=cal.get(Calendar.YEAR);
          int mon=cal.get(Calendar.MONTH);
          String mnth;
          if(mon==0)
            mnth="Jan";
         else  if(mon==1)
            mnth="Feb";
          else  if(mon==2)
            mnth="Mar";
          else  if(mon==3)
            mnth="Apr";
          else  if(mon==4)
            mnth="May";
          else  if(mon==5)
            mnth="Jun";
          else  if(mon==6)
            mnth="Jul";
          else  if(mon==7)
            mnth="Aug";
          else  if(mon==8)
            mnth="Sep";
          else  if(mon==9)
            mnth="Oct";
          else  if(mon==10)
            mnth="Nov";
          else
            mnth="Dec";
          String d=mnth+" "+day+","+" "+year;
         
          
        
        String category=(String)cmbcategory.getSelectedItem();
          if(cmbcategory.getSelectedIndex()==0)
       {
           JOptionPane.showMessageDialog(emp_detail.this,"Please select the category");
           cmbcategory.grabFocus();
           return;
       }
        String religion=(String)cmbreligion.getSelectedItem();
          if(cmbreligion.getSelectedIndex()==0)
       {
           JOptionPane.showMessageDialog(emp_detail.this,"Please select the religion");
           cmbreligion.grabFocus();
           return;
       }
        String nationality=(String)cmbnationality.getSelectedItem();
          if(cmbnationality.getSelectedIndex()==0)
       {
           JOptionPane.showMessageDialog(emp_detail.this,"Please select the nationality");
           cmbnationality.grabFocus();
           return;
       }
        String adhar=txtadhar.getText();
         if(txtadhar.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(emp_detail.this,"Please enter the adhaar no. ");
            txtadhar.grabFocus();
            return;
        }
        String pan=txtmobile.getText();
         if(txtmobile.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(emp_detail.this,"Please enter the mobile no. ");
            txtmobile.grabFocus();
            return;
        }
        String acct=txtacct.getText();
         if(txtacct.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(emp_detail.this,"Please enter the bank account no. ");
            txtacct.grabFocus();
            return;
        }
        String em=txtemail.getText();
         if(txtemail.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(emp_detail.this,"Please enter the email id  ");
            txtemail.grabFocus();
            return;
        }
        String mob=txtpan.getText();
         if(txtpan.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(emp_detail.this,"Please enter the pan card no. ");
            txtpan.grabFocus();
            return;
        }
        String marital=(String)cmbmarital.getSelectedItem();
         if(cmbmarital.getSelectedIndex()==0)
       {
           JOptionPane.showMessageDialog(emp_detail.this,"Please select the marital status of employee");
           cmbmarital.grabFocus();
           return;
       }
        String qualify=(String)cmbqualify.getSelectedItem();
          if(cmbqualify.getSelectedIndex()==0)
       {
           JOptionPane.showMessageDialog(emp_detail.this,"Please select the qualification of employee");
           cmbqualify.grabFocus();
           return;
       }
        String cad=caddress.getText();
         if(caddress.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(emp_detail.this,"Please enter the current address of employee ");
            caddress.grabFocus();
            return;
        }
         String pad=paddress.getText();
          if(paddress.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(emp_detail.this,"Please enter the permanent address  ");
            paddress.grabFocus();
            return;
        }
        String mname=txtmname.getText();
         if(txtmname.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(emp_detail.this,"Please enter the mother's name ");
            txtmname.grabFocus();
            return;
        }
        String fname=txtfname.getText();
         if(txtfname.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(emp_detail.this,"Please enter the adhaar no. ");
            txtfname.grabFocus();
            return;
        }
        String sname=txtsname.getText();
         if(txtsname.getText().trim().isEmpty())
        {
           txtsname.setText("N/A");
        }
          String child;
        try{
         child=txtchild.getText();
        }catch(NumberFormatException e)
        {
            JOptionPane.showMessageDialog(emp_detail.this,"please enter valid number in children's field");
            txtchild.grabFocus();
            return;
        }
         String mqualify=(String)cmbmqualify.getSelectedItem();
           if(cmbmqualify.getSelectedIndex()==0)
       {
           JOptionPane.showMessageDialog(emp_detail.this,"Please select the qualification of the mother of employee");
           cmbmqualify.grabFocus();
           return;
       }
          String fqualify=(String)cmbfqualify.getSelectedItem();
            if(cmbfqualify.getSelectedIndex()==0)
       {
           JOptionPane.showMessageDialog(emp_detail.this,"Please select the father's qualification of employee");
           cmbfqualify.grabFocus();
           return;
       }
          String squalify=(String)cmbsqualify.getSelectedItem();
          if(cmbsqualify.getSelectedIndex()==0)
           {
           JOptionPane.showMessageDialog(emp_detail.this,"Please select the spouse's qualification of employee");
           cmbsqualify.grabFocus();
           return;
       }
           String branch=(String)cmbbranch.getSelectedItem();
             if(cmbbranch.getSelectedIndex()==0)
           {
           JOptionPane.showMessageDialog(emp_detail.this,"Please select the branch of employee");
           cmbbranch.grabFocus();
           return;
       }
           String dept=(String)cmbdept.getSelectedItem();
             if(cmbdept.getSelectedIndex()==0)
           {
           JOptionPane.showMessageDialog(emp_detail.this,"Please select the department of employee");
           cmbdept.grabFocus();
           return;
       }
           String desg=(String)cmbdesig.getSelectedItem();
             if(cmbdesig.getSelectedIndex()==0)
           {
           JOptionPane.showMessageDialog(emp_detail.this,"Please select the designation of employee");
           cmbdesig.grabFocus();
           return;
       }
            String dr=txtdor.getText();
            Date dj1=doj.getDate();
            // Calendar cal1=Calendar.getInstance();
        cal.setTime(dj1);
        day=cal.get(Calendar.DAY_OF_MONTH);
          year=cal.get(Calendar.YEAR);
           mon=cal.get(Calendar.MONTH);
          
          if(mon==0)
            mnth="Jan";
         else  if(mon==1)
            mnth="Feb";
          else  if(mon==2)
            mnth="Mar";
          else  if(mon==3)
            mnth="Apr";
          else  if(mon==4)
            mnth="May";
          else  if(mon==5)
            mnth="Jun";
          else  if(mon==6)
            mnth="Jul";
          else  if(mon==7)
            mnth="Aug";
          else  if(mon==8)
            mnth="Sep";
          else  if(mon==9)
            mnth="Oct";
          else  if(mon==10)
            mnth="Nov";
          else
            mnth="Dec";
          String dj=mnth+" "+day+","+" "+year;
          
          
            //DateFormat df=new SimpleDateFormat("MMM DD, YYYY");
           // String jdate=df.format(dj);
           // String bdate=df.format(d);
          //String bdate="";
         // String jdate="";
        
       boolean f=false;
       try{
           
           Registry reg=LocateRegistry.getRegistry("127.0.0.1",1097);
           emp_detail_Interface i=(emp_detail_Interface )reg.lookup("emp_detail_insert");
           f=i.ins_empdetail( name, category,religion, acct, mqualify,fqualify,squalify, branch,dept,desg,d,gender, nationality, dj,dr,mob,em,cad, fname, mname,marital,sname,child, qualify, adhar, pan, pad);
           if(f==true)
                JOptionPane.showMessageDialog(null,"EMPLOYEE DETAILS INSERTED SUCCESFULLY");
           else
           JOptionPane.showMessageDialog(null,"EMPLOYEE DETAILS NOT INSERTED");    
       }catch(Exception e)
       {
           e.printStackTrace();

       }
            
                  
                     
            
           
    }//GEN-LAST:event_btnsubmitActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Admin().setVisible(true);
    }//GEN-LAST:event_btnbackActionPerformed

    private void txtemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemailActionPerformed

    private void txtmobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmobileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmobileActionPerformed

    private void cmbdeptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbdeptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbdeptActionPerformed

   
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(emp_detail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(emp_detail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(emp_detail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(emp_detail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new emp_detail().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnsubmit;
    private javax.swing.JTextArea caddress;
    private javax.swing.JComboBox<String> cmbbranch;
    private javax.swing.JComboBox<String> cmbcategory;
    private javax.swing.JComboBox<String> cmbdept;
    private javax.swing.JComboBox<String> cmbdesig;
    private javax.swing.JComboBox<String> cmbfqualify;
    private javax.swing.JComboBox<String> cmbgender;
    private javax.swing.JComboBox<String> cmbmarital;
    private javax.swing.JComboBox<String> cmbmqualify;
    private javax.swing.JComboBox cmbnationality;
    private javax.swing.JComboBox<String> cmbqualify;
    private javax.swing.JComboBox cmbreligion;
    private javax.swing.JComboBox<String> cmbsqualify;
    private com.toedter.calendar.JDateChooser dd;
    private com.toedter.calendar.JDateChooser doj;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea paddress;
    private javax.swing.JTextField txtacct;
    private javax.swing.JFormattedTextField txtadhar;
    private javax.swing.JTextField txtchild;
    private javax.swing.JTextField txtdor;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtfname;
    private javax.swing.JTextField txtmname;
    private javax.swing.JFormattedTextField txtmobile;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtpan;
    private javax.swing.JTextField txtsname;
    // End of variables declaration//GEN-END:variables
}
