
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author SHALU
 */
public class emptable extends javax.swing.JFrame {

    /**
     * Creates new form emptable
     */
     
   
           

    public emptable() {
        initComponents(); 
          try{
            String q="select * from update_employee";
            conn c1=new conn();
            ResultSet rs=c1.s.executeQuery(q);
            while(rs.next()){
        Object[] row ={rs.getString("id"),rs.getString("name"),rs.getString("desg"),rs.getString("dob"),rs.getString("gender"),rs.getString("nationality"),
        rs.getString("jdate"),rs.getString("rdate"),rs.getString("mobile"),rs.getString("email"),rs.getString("caddress"),rs.getString("fname"),rs.getString("mname")
      ,rs.getString("marital"),rs.getString("spouse"),rs.getString("children"),rs.getString("qualification"),rs.getString("pan"),rs.getString("adahr"),rs.getString("paddress"), rs.getString("m_qualification"),
        rs.getString("f_qualification"),rs.getString("s_qualification"),rs.getString("acc_num"),rs.getString("category"),rs.getString("department"),rs.getString("branch")
        ,rs.getString("religion")};
        DefaultTableModel model=(DefaultTableModel) J1.getModel();
        model.addRow(row);
            }}


 catch(Exception e){}
          
             
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        J1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1400, 700));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        J1.setBackground(new java.awt.Color(0, 0, 51));
        J1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        J1.setForeground(new java.awt.Color(255, 255, 255));
        J1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NAME", "DESIGNATION", "D.O.B", "GENDER", "NATIONALITY", "DATE OF JOINING", "RETIREMENT DATE", "CONTACT NO.", "EMAIL", "CURRENT ADDRESS", "FATHERS' NAME", "MOTHERS' NAME", "MARITAL STATUS", "SPOUSE", "CHILDREN", "QUALIFICATION", "PAN NO.", "ADHAR NO.", "PERMANENT ADDRESS", "MOTHERS' QUALIFICATION", "FATHERS'  QUALIFICATION", "SPOUSES' QUALIFICATION", "BANK ACCOUNT NO.", "CATEGORY", "DEPARTMENT", "BRANCH", "RELIGION"
            }
        ));
        J1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        J1.setGridColor(new java.awt.Color(0, 0, 0));
        J1.setPreferredSize(new java.awt.Dimension(2100, 700));
        J1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                J1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(J1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 608, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void J1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_J1MouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_J1MouseClicked

         
          

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
        // TODO add your handling code here:
        
         
        
    }//GEN-LAST:event_jScrollPane1MouseClicked
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(emptable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(emptable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(emptable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(emptable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new emptable().setVisible(true);
               
        }
        });}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable J1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
