
import java.awt.Frame;
import java.sql.ResultSet;
import static javafx.beans.binding.Bindings.and;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author SHALU
 */
public class login_as extends javax.swing.JFrame {

    /**
     * Creates new form login_as
     */
    public login_as() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
   @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtbs = new javax.swing.JTextField();
        txtpf = new javax.swing.JTextField();
        txtda = new javax.swing.JTextField();
        txthra = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        cmbdesg = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        txtperks = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cmbbranch = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SALARY");
        setBackground(new java.awt.Color(248, 148, 6));

        jPanel2.setBackground(new java.awt.Color(44, 62, 80));

        jLabel5.setFont(new java.awt.Font("Jokerman", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("DESIGNATION");

        jLabel6.setFont(new java.awt.Font("Jokerman", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setText("BASIC SALARY");

        jLabel7.setFont(new java.awt.Font("Jokerman", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(240, 240, 240));
        jLabel7.setText("HRA");

        jLabel8.setFont(new java.awt.Font("Jokerman", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(240, 240, 240));
        jLabel8.setText("DA");

        jLabel10.setFont(new java.awt.Font("Jokerman", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(240, 240, 240));
        jLabel10.setText("PF DEDUCTION RATE");

        txtbs.setBackground(new java.awt.Color(108, 122, 137));
        txtbs.setFont(new java.awt.Font("Jokerman", 1, 14)); // NOI18N
        txtbs.setForeground(new java.awt.Color(240, 240, 240));
        txtbs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbsActionPerformed(evt);
            }
        });

        txtpf.setBackground(new java.awt.Color(108, 122, 137));
        txtpf.setFont(new java.awt.Font("Jokerman", 1, 14)); // NOI18N
        txtpf.setForeground(new java.awt.Color(240, 240, 240));
        txtpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpfActionPerformed(evt);
            }
        });

        txtda.setBackground(new java.awt.Color(108, 122, 137));
        txtda.setFont(new java.awt.Font("Jokerman", 1, 14)); // NOI18N
        txtda.setForeground(new java.awt.Color(240, 240, 240));
        txtda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdaActionPerformed(evt);
            }
        });

        txthra.setBackground(new java.awt.Color(108, 122, 137));
        txthra.setFont(new java.awt.Font("Jokerman", 1, 14)); // NOI18N
        txthra.setForeground(new java.awt.Color(240, 240, 240));
        txthra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthraActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setFont(new java.awt.Font("Jokerman", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(51, 51, 51));
        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 0, 0));
        jButton3.setFont(new java.awt.Font("Jokerman", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(51, 51, 51));
        jButton3.setText("UPDATE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        cmbdesg.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Select Designation--", "Clerk", "Assistant Manager", "Manager", "Senior Manager", "Chief Manager", "Assistant General Manager", "Deputy General Manager", "General Manager", "Executive Director", "Chairman" }));
        cmbdesg.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbdesgItemStateChanged(evt);
            }
        });
        cmbdesg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbdesgActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Jokerman", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(240, 240, 240));
        jLabel12.setText("PERKS");

        txtperks.setBackground(new java.awt.Color(108, 122, 137));
        txtperks.setFont(new java.awt.Font("Jokerman", 1, 14)); // NOI18N
        txtperks.setForeground(new java.awt.Color(240, 240, 240));
        txtperks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtperksActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Jokerman", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(240, 240, 240));
        jLabel9.setText("BRANCH");

        cmbbranch.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Select Branch--", "Bengaluru", "Kolkata", "Lucknow", "Mumbai", "New Delhi", "Patna", "Raipur", "Ranchi" }));
        cmbbranch.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbbranchItemStateChanged(evt);
            }
        });
        cmbbranch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbbranchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtperks, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtbs, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton2)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtpf, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel9))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7)))
                            .addComponent(jLabel5))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(240, 240, 240)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbdesg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbbranch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtda, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txthra, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(161, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(cmbdesg, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(cmbbranch, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9)))
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txtbs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel8))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(txtda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabel7)
                                .addGap(38, 38, 38)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(txtperks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(txthra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(27, 27, 27)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(51, 51, 51)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(234, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtbsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbsActionPerformed

    private void txtpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpfActionPerformed

    private void txtdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdaActionPerformed

    private void txthraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthraActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
            String n = (String) cmbdesg.getSelectedItem();
            String g = txtbs.getText();
            String a = txthra.getText();
            String s = txtda.getText();
           // String c = txtma.getText();
            String e = txtpf.getText();
            String b= (String) cmbbranch.getSelectedItem();
          //  String p = txttds.getText();
            String r=txtperks.getText();
            
            String qry = "update update_salary set desg='"+n+"',bs='"+g+"',rhra='"+a+"',da='"+s+"',perks='"+r+"',pf='"+e+"'  where desg='"+(String)cmbdesg.getSelectedItem()+"' and branch='"+b+"'";
            String qry1 = "update update_salary set desg='"+n+"',bs='"+g+"',chra='"+a+"',da='"+s+"',perks='"+r+"',pf='"+e+"'  where desg='"+(String)cmbdesg.getSelectedItem()+"' and branch='"+b+"'";        
       String qry2 = "update update_salary set desg='"+n+"',bs='"+g+"',mhra='"+a+"',da='"+s+"',perks='"+r+"',pf='"+e+"'  where desg='"+(String)cmbdesg.getSelectedItem()+"' and branch='"+b+"'";
            try{
                conn c1 = new conn();
                 if(b.equals("Bengaluru")||b.equals("New Delhi")||b.equals("Kolkata")||b.equals("Mumbai"))
                c1.s.executeUpdate(qry2);
                 else if(b.equals("Lucknow")||b.equals("Patna")||b.equals("Raipur")||b.equals("Ranchi"))
                     c1.s.executeUpdate(qry1);
                     
                     else
                         c1.s.executeUpdate(qry);
                JOptionPane.showMessageDialog(null,"Salary Updated");
            }catch(Exception ee){
                ee.printStackTrace();
            }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void cmbdesgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbdesgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbdesgActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         new Admin().setVisible(true);
                setVisible(false);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cmbdesgItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbdesgItemStateChanged
       
    }//GEN-LAST:event_cmbdesgItemStateChanged

    private void txtperksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtperksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtperksActionPerformed

    private void cmbbranchItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbbranchItemStateChanged
        // TODO add your handling code here:
        int t;
        String  xx;
       t= cmbdesg.getSelectedIndex(); 
       if(t==0)
       {
           JOptionPane.showMessageDialog(null,"First select Designation");
           cmbdesg.grabFocus();
           
       }
       else{
            try{
            conn c1 = new conn();
            ResultSet rs = c1.s.executeQuery("select * from update_salary where desg='"+(String)cmbdesg.getSelectedItem()+"'and branch='"+(String)cmbbranch.getSelectedItem()+"'");
            
            if(rs.next()){
                txtbs.setText(rs.getString("bs"));
                xx=rs.getString("branch");
                if(xx.equals("Bengaluru")||xx.equals("New Delhi")||xx.equals("Kolkata")||xx.equals("Mumbai"))
                txthra.setText(rs.getString("mhra"));
                else if(xx.equals("Lucknow")||xx.equals("Patna")||xx.equals("Raipur")||xx.equals("Ranchi"))
                txthra.setText(rs.getString("chra"));
                 else
                 txthra.setText(rs.getString("rhra"));    
             txtda.setText(rs.getString("da"));
                txtpf.setText(rs.getString("pf"));
               
                txtperks.setText(rs.getString("perks"));
            }
        }catch(Exception ee){
           ee.printStackTrace();
        }
           
       }
        
    }//GEN-LAST:event_cmbbranchItemStateChanged

    private void cmbbranchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbbranchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbbranchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login_as.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login_as.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login_as.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login_as.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login_as().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbbranch;
    private javax.swing.JComboBox cmbdesg;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtbs;
    private javax.swing.JTextField txtda;
    private javax.swing.JTextField txthra;
    private javax.swing.JTextField txtperks;
    private javax.swing.JTextField txtpf;
    // End of variables declaration//GEN-END:variables
}
